#!/usr/bin/env bash

if [ ! -d "$HOME/Downloads" ]; then
    echo "Downloads directory not found"
    exit 1
fi

find $HOME/Downloads/* -type f -mtime +2 -delete -print
find $HOME/Downloads/* -type d -mtime +2 -empty -delete -print
