
[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[window]
opacity = 0.85

[general]

live_config_reload = true
import = ["~/.config/alacritty/theme.toml"]

[terminal]

[terminal.shell]
program = "zellij"
